POST http://127.0.0.1:4004/send HTTP/1.1
Authorization: key=asdasdlkjaskldbabdknasdnaslndlasndl'k
Content-Type: application/json

{
    "to": "123123",
    "data": {
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
	    "action": "add",
        "itemtype": "shipping",
        "value": ""
    },
    "notification": {
        "title": "aaaaa"
    }
}

###

POST http://127.0.0.1:4004/v1/projects/my-awesome-project/messages:send HTTP/1.1
Authorization: Bearer asdasdlkjaskldbabdknasdnaslndlasndl'k
Content-Type: application/json

{
    "Message" : {
        "token": "123123",
        "data": {
            "click_action": "FLUTTER_NOTIFICATION_CLICK",
            "action": "add",
            "itemtype": "shipping",
            "value": ""
        },
        "notification": {
            "title": "aaaaa"
        }
    }
}

###

GET http://127.0.0.1:4004/api/messages HTTP/1.1

###

DELETE http://127.0.0.1:4004/api/messages HTTP/1.1